Add Soundex
stats4sd/tpp-metrics-library pull request #50
Opened 2024-03-21 09:26 UTC by dan-tang-ssd

This PR is submitted to fix #30.

It is not yet ready for review, it is submitted for status update.

TODO:
- [ ] Add a command to calculate and store soundex result of entity name to soundex column in different entity tables
- [ ] In Dimension entry View page, add a modal popup form to show possible duplicates (other dimension entries with same soundex value) as a checklist
- [ ] Allow user to select entries and merge (use script that merges the relationships)
- [ ] Allow user to mark the entries as not duplicates so they don't appear again as possible duplicates

2024-03-27 10:25 UTC, dan-tang-ssd commented
WIP: In Dimension page, add a button to show potential duplicates (with same soundex value of current record) in modal popup.

---

Screen shots:

![image](https://github.com/stats4sd/tpp-metrics-library/assets/86968034/8f7bb9ed-28ef-4c77-a99f-a9dd465228cb)

![image](https://github.com/stats4sd/tpp-metrics-library/assets/86968034/3e1c5df9-1529-49c2-ab05-9d577b66e864)

2024-03-27 14:20 UTC, dan-tang-ssd commented
I have added (copied) business logic for de-duplication from table bulk action "DeduplicateRecordsAction".

I think it is now ready for review.

---

As Deduplicate is a table row button, I assume user is going to merge the selected potential duplicates to the currently viewing dimension entry. Therefore I skipped the "select one to remain" step.

Some other changes:
1. I splitted "Deduplicate" and "Mark as not duplicate" as two separate table row actions.
2. In Dimension view page, I add the counter for tools relationship.

2024-03-27 14:49 UTC, dave-mills requested changes
Functionality looks good. The deduplication and marking entries as not duplicates works as expected. 

### A few UI / UX comments:

- The 'selected' dimension isn't shown anywhere in the modals. I want to know what dimension am I comparing the listed ones to.
- When I see "mark as not duplicate" as a button in the table, it looks like I am about to mark that entry as not a duplicate, rather than review possible duplicates and declare they are not duplicates. 

I am not convinced these work as separate functions - consider possible workflows:
- For a specific dimension, I first want to see what possible duplicates the system has identified. 
- I may want to review the main entry for these possible duplicates (can I open a view page for some of the possible duplicates in a new tab?)
- I then can make a decision for each possible duplicate - is it really a duplicate? Or is it not? 


### Soundex review
Looking at some of the items, I think the soundex is good as a tool, but gives a lot of false positives (check out the screenshot below, which is the identified duplicates for "agricultural runoff" - you don't have to know what that means to notice how widely different the items in this list are). So, while I'm happy keeping the soundex, we definitely need other ways to help us identify duplicates or 'similar-enough' entries. 


![CleanShot 2024-03-27 at 14 47 32](https://github.com/stats4sd/tpp-metrics-library/assets/5711101/4476a40d-d85e-42e4-8d37-d0e08b46f4e2)

2024-03-27 16:52 UTC, dave-mills commented
Re: the 2 separated functions - after looking at it a bit more, I agree that we probably shouldn't have both options (merge or mark as not-duplicate) in the same modal popup, at least without a bit more careful UI / UX planning than we have time for. So for now I've removed the 'mark as not duplicate' option from the table. (We could maybe bring it back in on the view page).

Re: Soundex being quite a blunt tool - Looking at the soundex() [page](https://www.php.net/manual/en/function.soundex.php) I saw a reference to metaphone() (under "see also"). I tried that out and it much narrower in identifying duplicates (perhaps too narrow). 

My assessment is that duplicates identified through soundex are "possible" duplicates (but likely not duplicates), while entries with identical metaphone strings are very likely to be duplicates!. 

I have added both lists to the modal popup with an explanation of each, and added icons into the table to show whether an entry has 'likely' duplicates (metaphone) or 'possible' duplicates (soundex).

2024-03-27 16:53 UTC, dave-mills commented on app/Console/Commands/AddMetaphoneToEntities.php
> +//        $this->addMetaphone(Theme::class, 'name');
Testing with just dimensions for now

2024-04-02 08:46 UTC, dave-mills commented
I think from here we should:

- enable generation of both metaphone and soundex for all the data models;
- merge this into dev and publish it to the staging site along with the other changes.

@dan-tang-ssd can you do this?

2024-04-02 08:53 UTC, dan-tang-ssd commented
> I think from here we should:
> 
>     * enable generation of both metaphone and soundex for all the data models;
> 
>     * merge this into dev and publish it to the staging site along with the other changes.
> 
> 
> @dan-tang-ssd can you do this?

Yes, it sounds good.

Should we merge this PR into dev and publish it to staging env first, and then add "Deduplicate" feature to all other entities?

2024-04-02 14:56 UTC, dave-mills commented
@dan-tang-ssd - so '12' is a good number for the metaphone from your testing? Sure - lets go for that if you think that gives some better results. 

Once you've enabled the generation of soundex and metaphone for the other entities, this is good to merge in.

2024-04-04 10:18 UTC, dan-tang-ssd commented
> @dan-tang-ssd - so '12' is a good number for the metaphone from your testing? Sure - lets go for that if you think that gives some better results.

I did some testing and sampling before, it seems that "12" is a good comprimise. 
Yes, we can finetune it when necessary.

Below please find some sampling for "10", "12" and "15" for quick reference.

---

metaphone "10"

![image](https://github.com/stats4sd/tpp-metrics-library/assets/86968034/51a2570e-5737-4322-97cd-0e9327793c8e)

---

metaphone "12"

![image](https://github.com/stats4sd/tpp-metrics-library/assets/86968034/0a29f4ef-f92f-4000-b48b-14dec2a5acad)

---

metaphone "15"

![image](https://github.com/stats4sd/tpp-metrics-library/assets/86968034/ba2e1bd9-d7c5-49e7-8bce-dfd29a35caba)

2024-04-04 10:20 UTC, dan-tang-ssd commented
> Once you've enabled the generation of soundex and metaphone for the other entities, this is good to merge in.

I am going to merge this PR into dev branch now.

I would enable the generation of soundex and metaphone for other entities in future PR that we add "Deplicate" feature to them.

2024-04-04 10:26 UTC, merged

2024-04-04 10:34 UTC, dan-tang-ssd commented
In staging env, deployment is done automatically as "Quick Deploy" is enabled.

I checked latest deployment log, error occurred when executing command "npm run build".
"npm run build" was commented in deployment script originally. I have enabled this command when comparing with AEC staging env.

I have just commented command "npm run build" in deployment script, manual triggered "Deploy Now".
Staging env deployment is completed successfully now.